=== vemser/captacao-api-qa/src/test/resources/schemas/ListarCandidato.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "totalElementos": {
      "type": "integer"
    },
    "quantidadePaginas": {
      "type": "integer"
    },
    "pagina": {
      "type": "integer"
    },
    "tamanho": {
      "type": "integer"
    },
    "elementos": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "idCandidato": {
              "type": "integer"
            },
            "nome": {
              "type": "string"
            },
            "dataNascimento": {
              "type": "string"
            },
            "email": {
              "type": "string"
            },
            "telefone": {
              "type": "string"
            },
            "rg": {
              "type": "string"
            },
            "cpf": {
              "type": "string"
            },
            "estado": {
              "type": "string"
            },
            "cidade": {
              "type": "string"
            },
            "statusCandidato": {
              "type": "string"
            },
            "pcd": {
              "type": "string"
            },
            "observacoes": {
              "type": ["string", "null"]
            },
            "notaProva": {
              "type":  ["number", "null"]
            },
            "notaEntrevistaComportamental": {
              "type":  ["number", "null"]
            },
            "notaEntrevistaTecnica": {
              "type":  ["number", "null"]
            },
            "ativo": {
              "type": "string"
            },
            "parecerComportamental": {
              "type": ["string", "null"]
            },
            "parecerTecnico": {
              "type": ["string", "null"]
            },
            "media": {
              "type": ["integer", "null"]
            },
            "linguagens": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "nome": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "nome"
                  ]
                }
              ]
            },
            "edicao": {
              "type": "object",
              "properties": {
                "idEdicao": {
                  "type": "integer"
                },
                "nome": {
                  "type": "string"
                },
                "notaCorte": {
                  "type":  ["number", "null"]
                }
              },
              "required": [
                "idEdicao",
                "nome",
                "notaCorte"
              ]
            },
            "formulario": {
              "type": "object",
              "properties": {
                "idFormulario": {
                  "type": "integer"
                },
                "matriculado": {
                  "type": "string"
                },
                "curso": {
                  "type": "string"
                },
                "turno": {
                  "type": "string"
                },
                "instituicao": {
                  "type": "string"
                },
                "github": {
                  "type": "string"
                },
                "linkedin": {
                  "type": "string"
                },
                "desafios": {
                  "type": "string"
                },
                "problema": {
                  "type": "string"
                },
                "reconhecimento": {
                  "type": "string"
                },
                "altruismo": {
                  "type": "string"
                },
                "resposta": {
                  "type": "string"
                },
                "curriculo": {
                  "type": ["integer", "null"]
                },
                "lgpd": {
                  "type": "string"
                },
                "prova": {
                  "type": "string"
                },
                "ingles": {
                  "type": "string"
                },
                "espanhol": {
                  "type": "string"
                },
                "neurodiversidade": {
                  "type": "string"
                },
                "efetivacao": {
                  "type": "string"
                },
                "genero": {
                  "type": "string"
                },
                "orientacao": {
                  "type": "string"
                },
                "disponibilidade": {
                  "type": "string"
                },
                "trilhas": {
                  "type": "array",
                  "items": [
                    {
                      "type": "object",
                      "properties": {
                        "nome": {
                          "type": "string"
                        },
                        "idTrilha": {
                          "type": "integer"
                        }
                      },
                      "required": [
                        "nome",
                        "idTrilha"
                      ]
                    }
                  ]
                },
                "imagemConfigPc": {
                  "type": ["integer", "null"]
                },
                "qtdSemestres": {
                  "type": "integer"
                },
                "semestreAtual": {
                  "type": "integer"
                },
                "tipoGraduacao": {
                  "type": "string"
                },
                "descConfigPc": {
                  "type": "string"
                },
                "importancia": {
                  "type": "string"
                }
              },
              "required": [
                "idFormulario",
                "matriculado",
                "curso",
                "turno",
                "instituicao",
                "github",
                "linkedin",
                "desafios",
                "problema",
                "reconhecimento",
                "altruismo",
                "resposta",
                "curriculo",
                "lgpd",
                "prova",
                "ingles",
                "espanhol",
                "neurodiversidade",
                "efetivacao",
                "genero",
                "orientacao",
                "disponibilidade",
                "trilhas",
                "imagemConfigPc",
                "qtdSemestres",
                "semestreAtual",
                "tipoGraduacao",
                "descConfigPc",
                "importancia"
              ]
            },
            "imagem": {
              "type": ["integer", "null"]
            }
          },
          "required": [
            "idCandidato",
            "nome",
            "dataNascimento",
            "email",
            "telefone",
            "rg",
            "cpf",
            "estado",
            "cidade",
            "statusCandidato",
            "pcd",
            "observacoes",
            "notaProva",
            "notaEntrevistaComportamental",
            "notaEntrevistaTecnica",
            "ativo",
            "parecerComportamental",
            "parecerTecnico",
            "media",
            "linguagens",
            "edicao",
            "formulario",
            "imagem"
          ]
        }
      ]
    }
  },
  "required": [
    "totalElementos",
    "quantidadePaginas",
    "pagina",
    "tamanho",
    "elementos"
  ]
}

=== vemser/captacao-api-qa/src/test/resources/schemas/entrevista/listar_entrevistas_por_mes.json
{
  "totalElementos": 2,
  "quantidadePaginas": 1,
  "pagina": 0,
  "tamanho": 20,
  "elementos": [
    {
      "candidatoEmail": "analivia.damaia@gmail.com",
      "dataEntrevista": "2025-09-18T01:00:17.953",
      "observacoes": "teste",
      "avaliado": "T",
      "idEntrevista": 2,
      "candidatoDTO": {
        "idCandidato": 17,
        "nome": "Sirineu Banheira",
        "dataNascimento": "1978-02-28",
        "email": "analivia.damaia@gmail.com",
        "telefone": "(31) 93230-2318",
        "rg": "459408569",
        "cpf": "801.736.011-89",
        "estado": "AC",
        "cidade": "Carnaíba",
        "statusCandidato": "PENDENTE",
        "pcd": "Não possui",
        "observacoes": null,
        "notaProva": 0.0,
        "notaEntrevistaComportamental": 0.0,
        "notaEntrevistaTecnica": 0.0,
        "ativo": "T",
        "parecerComportamental": null,
        "parecerTecnico": null,
        "media": null,
        "linguagens": [
          {
            "nome": "JAVA"
          }
        ],
        "edicao": {
          "idEdicao": 69,
          "nome": "VEMSER_25073",
          "notaCorte": 60.0
        },
        "formulario": {
          "idFormulario": 239,
          "matriculado": "T",
          "curso": "Bachelor of Psychology",
          "turno": "MANHA",
          "instituicao": "Centro Tecnológico Metodista do Tocantins do Sudeste",
          "github": "https://www.github.com",
          "linkedin": "https://www.linkedin.com",
          "desafios": "T",
          "problema": "F",
          "reconhecimento": "F",
          "altruismo": "T",
          "resposta": "quam",
          "curriculo": null,
          "lgpd": "T",
          "prova": "T",
          "ingles": "id",
          "espanhol": "accusamus",
          "neurodiversidade": "consectetur",
          "efetivacao": "T",
          "genero": "Female",
          "orientacao": "Female",
          "disponibilidade": "F",
          "trilhas": [
            {
              "nome": "FRONTEND",
              "idTrilha": 1
            }
          ],
          "imagemConfigPc": null,
          "qtdSemestres": 0,
          "semestreAtual": 1,
          "tipoGraduacao": "Graduation",
          "descConfigPc": "Description of PC configuration",
          "importancia": "fuga"
        },
        "imagem": null
      },
      "gestorDTO": {
        "idGestor": 4,
        "nome": "rafael isidro",
        "email": "rafael.isidro",
        "cargosDto": [
          {
            "idCargo": 2,
            "nome": "ROLE_INSTRUTOR"
          },
          {
            "idCargo": 3,
            "nome": "ROLE_GESTAO_DE_PESSOAS"
          },
          {
            "idCargo": 4,
            "nome": "ROLE_ADMIN"
          }
        ],
        "ativo": "T"
      },
      "legenda": "PENDENTE"
    },
    {
      "candidatoEmail": "gubio.moniz@bol.com.br",
      "dataEntrevista": "2025-09-18T09:48:30.519",
      "observacoes": "Ea consequatur reiciendis maiores sint mollitia voluptate architecto.",
      "avaliado": "T",
      "idEntrevista": 3,
      "candidatoDTO": {
        "idCandidato": 23,
        "nome": "Helena Marcondes",
        "dataNascimento": "2003-04-19",
        "email": "gubio.moniz@bol.com.br",
        "telefone": "(77) 95884-3271",
        "rg": "307456714",
        "cpf": "158.776.623-09",
        "estado": "BA",
        "cidade": "Malhada",
        "statusCandidato": "PENDENTE",
        "pcd": "Não possui",
        "observacoes": null,
        "notaProva": 0.0,
        "notaEntrevistaComportamental": 0.0,
        "notaEntrevistaTecnica": 0.0,
        "ativo": "T",
        "parecerComportamental": null,
        "parecerTecnico": null,
        "media": null,
        "linguagens": [
          {
            "nome": "JAVA"
          }
        ],
        "edicao": {
          "idEdicao": 91,
          "nome": "VEMSER_69397",
          "notaCorte": 60.0
        },
        "formulario": {
          "idFormulario": 245,
          "matriculado": "T",
          "curso": "Master of Business",
          "turno": "MANHA",
          "instituicao": "Universidade da Bandeira",
          "github": "https://www.github.com",
          "linkedin": "https://www.linkedin.com",
          "desafios": "F",
          "problema": "T",
          "reconhecimento": "T",
          "altruismo": "T",
          "resposta": "ut",
          "curriculo": null,
          "lgpd": "F",
          "prova": "F",
          "ingles": "quia",
          "espanhol": "quod",
          "neurodiversidade": "consequatur",
          "efetivacao": "F",
          "genero": "Male",
          "orientacao": "Female",
          "disponibilidade": "F",
          "trilhas": [
            {
              "nome": "FRONTEND",
              "idTrilha": 1
            }
          ],
          "imagemConfigPc": null,
          "qtdSemestres": 0,
          "semestreAtual": 1,
          "tipoGraduacao": "Graduation",
          "descConfigPc": "Description of PC configuration",
          "importancia": "sed"
        },
        "imagem": null
      },
      "gestorDTO": {
        "idGestor": 4,
        "nome": "rafael isidro",
        "email": "rafael.isidro",
        "cargosDto": [
          {
            "idCargo": 2,
            "nome": "ROLE_INSTRUTOR"
          },
          {
            "idCargo": 3,
            "nome": "ROLE_GESTAO_DE_PESSOAS"
          },
          {
            "idCargo": 4,
            "nome": "ROLE_ADMIN"
          }
        ],
        "ativo": "T"
      },
      "legenda": "PENDENTE"
    }
  ]
}
